"""empty message

Revision ID: 163dd3b899f7
Revises: 89d578419633
Create Date: 2021-04-27 13:41:47.550109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163dd3b899f7'
down_revision = '89d578419633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
