"""empty message

Revision ID: 5b32eeb0a45c
Revises: f41ad26cff3e
Create Date: 2021-05-04 11:16:02.395917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b32eeb0a45c'
down_revision = 'f41ad26cff3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
