"""empty message

Revision ID: 99b69293f171
Revises: 1dc0338dcc38
Create Date: 2021-04-26 10:47:21.016604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b69293f171'
down_revision = '1dc0338dcc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.alter_column('artist', 'seeking', nullable=False, new_column_name='seeking_venue')
    op.alter_column('venue', 'seeking', nullable=False, new_column_name='seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('venue', 'seeking_talent')
    op.add_column('artist', sa.Column('seeking', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
